# Resources
In the workshop, we learned the basics of building a webpage that contains an interactive web map.  We learned some basic HTML and javascript, in particular the Leaflet javascript library.  There is so much more you can learn and create! Here are some resources to help you build on the skills you learned in this workshop:

[Leaflet Reference](https://leafletjs.com/) - tutorials and documentation for the Leaflet javascript library

[W3Schools](https://www.w3schools.com/) - a good reference for HTML, CSS, & general javascript

[Leafmap Basemap Search Tool](https://leafmap.org/notebooks/31_search_basemaps/) - this is a python package, so it's not directly applicable to this workshop, however it may be useful to help you discover other basemap options or point you to sources you didn't know about

[OpenPlanetary Basemaps](https://www.openplanetary.org/opm/basemaps) - a place to find basemaps for web maps of non-Earth planets; at the time of writing, The Moon and Mars were available.

[Programming Historian walk through](https://programminghistorian.org/en/lessons/mapping-with-python-leaflet)

[Anatomy of a web map presentation](http://maptime.io/anatomy-of-a-web-map/)

[leaflet R package](https://rstudio.github.io/leaflet/)

[Github Pages Documentation](https://docs.github.com/en/pages)

[Open-Source Web-GIS Development Roadmap](https://www.gislounge.com/open-source-web-gis-development-roadmap/) - How to develop your skills for web-based spatial tools and maps