#INTRODUCTION:
# This code looks for <highlight> & </highlight> tags in the html files generated by bookdown and replaces them with html span tags that highlight the text in your chosen color, using yellow as the default.

# INSTRUCTIONS:
#   1. Write your .Rmd files using <highlight> & </highlight> tags to indicate the start and end of the text you want to highlight. Note that code blocks must be plain - just back ticks - no programming language indicated.
#   2. Set your working directory to the root of your github repo folder for the bookdown project
#   3. Run the bookdown code to knit your .Rmd files to html
#   4. Run this file to highlight the areas you indicated in your .Rmd file
#   5. Commit and push the changes to the online repository.

# Set Up ------------------------------------------------------------------

# install libraries
install.packages("brio")

# load libraries
library(brio) #brio reads and writes UTF-8 files


#  Function: bookdown_highlight -----------------------------------------

#define a function that highlights the code

bookdown_highlight<-function(color='#ffff7f'){
  # get the html files
  file_list<-list.files(path= "./docs", pattern = "\\.html$")
  
  for (i in file_list){

    #read the file
    file_path<- paste0("./docs/", i)

    doc_text<- brio::readLines(file_path)
    
    #replace the opening markup tag with the html tag
    highlight_span<-paste0('<span style="background-color:', color, '">')
    
    new_text<-gsub(
      pattern="&lt;highlight&gt;", 
      replacement = highlight_span, 
      x=doc_text
      )
    
    #replace the closing markup tag with the html tag
    new_text<-gsub(
      pattern="&lt;/highlight&gt;", 
      replacement ="</span>", 
      x=new_text
      )
    
    #write(new_text, file=file_path)
    brio::write_lines(text=new_text, path=file_path)
    
    }
  
  print("Your bookdown files are highlighted!")
  
}

#run the function on the code
bookdown_highlight()


